{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "clearvoice.fullname" . }}-external-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "clearvoice.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
  target:
    name: {{ .Values.externalSecrets.targetSecretName | quote }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property | quote }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version | quote }}
        {{- end }}
    {{- end }}
{{- end }}
