{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clearvoice.fullname" . }}-api
  labels:
    {{- include "clearvoice.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.api.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
{{- if .Values.ui.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clearvoice.fullname" . }}-ui
  labels:
    {{- include "clearvoice.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ui.serviceAccount.annotations | nindent 4 }}
{{- end }}
